module.exports = {
    "Success" :"Success",
    "ServerError": "Server error occurred, Please try again",
    "serverError": "Server error occurred, Please try again",
    "PasswordError": "Invalid Password.",
    "missingParamError": "Please check the details again, something is wrong",
    "invalidEmail": "Please enter a valid Email ID",
    "invalidToken": "Invalid Token, Please check again",
    "emailValidationError": "Please enter a valid Email Address",
    "missingParams":"Please complete all the fields to continue",
    "passwordValidationError": "Please enter a valid Password",
    "registerSuccess": "Registration Completed Successfully",
    "loginSuccess": "Login Successful",
    "deleteUser": "User has been Deleted Successfully",
    "registerSuccess": "Registration Completed Successfully",
    "emailExistError": "A user with this email address already exists.",
    "tokenExpired": "Unauthorised! Access Denied",
    "rightsFail": "You are not authorised to perform this Action",
    "updateUserSuccess":"User Updated Successfully"
} 